In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
from task6 import task

s = "[[1, 2, 1.5], [3,2,3], [2, 2, 1.5]]"
task(s)

[0.336, 0.295, 0.369]

In [3]:
json_str = '[[1,3,2],[2,2,2],[1.5,3,1.5]]'
result = task(json_str)
expected = [0.468, 0.169, 0.363]
print(result)
print('Result is as Expected:', result == expected)

[0.468, 0.169, 0.363]
Result is as Expected: True


In [4]:
s = "[[1,2,1.5],[3,2,3],[2,2,1.5]]"
task(s)

[0.336, 0.295, 0.369]

In [20]:
df = pd.read_csv("test2.csv", header=None).to_numpy()

In [23]:
df

array([[1. , 2. , 1.5],
       [3. , 2. , 3. ],
       [2. , 2. , 1.5]])

In [24]:
df[0]

array([1. , 2. , 1.5])

In [31]:
r = []
for i in range(df.shape[1]):
    r_i = []
    for j in range(df.shape[0]):
        r_ij = []
        for k in range(df.shape[0]):
            if df[j][i] == df[k][i]:
                r_ij.append(0.5)
            elif df[j][i] > df[k][i]:
                r_ij.append(0)
            else:
                r_ij.append(1)
        r_i.append(r_ij)
    r.append(r_i)

In [34]:
r = np.array(r)

In [59]:
r.mean(0)

array([[0.5       , 0.83333333, 0.66666667],
       [0.16666667, 0.5       , 0.16666667],
       [0.33333333, 0.83333333, 0.5       ]])

In [60]:
x = r.mean(0)

In [61]:
k = np.array([1/3, 1/3, 1/3])
k_old = k.copy()

In [62]:
E = 0.001
while np.linalg.norm(k - k_old) < E:
    k_old = k.copy()
    y = x @ k
    lmd = np.array([1.0, 1.0, 1.0]) @ (x @ k)
    k = (1 / lmd) * y
    

In [63]:
k

array([0.44444444, 0.18518519, 0.37037037])